[package]
name = "wrapped-decimal"
version = "0.1.5"
edition = "2021"
description = "POD-safe 16-byte wrapper for rust_decimal::Decimal."
license = "MIT"
repository = "https://github.com/ChiefWoods/solana-math"
homepage = "https://github.com/ChiefWoods/solana-math"
documentation = "https://docs.rs/wrapped-decimal"
readme = "README.md"
keywords = ["solana", "decimal", "math", "serialization"]
categories = ["cryptography::cryptocurrencies", "data-structures", "mathematics"]
rust-version = "1.85"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE*", "CHANGELOG.md"]

[features]
default = []
std = []
anchor = ["std", "dep:anchor-lang"]
codama = ["dep:codama"]
idl-build = ["anchor", "anchor-lang/idl-build"]

[dependencies]
anchor-lang = { workspace = true, optional = true }
bytemuck = { workspace = true }
codama = { workspace = true, optional = true }
rust_decimal = { workspace = true }

[dev-dependencies]
husky-rs = { workspace = true }

[package.metadata.docs.rs]
all-features = true
