# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = """
## What's new
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}\
    {% for commit in commits %}
        - {{ commit.message | upper_first | split(pat="\n") | first | trim }}\
        {% if commit.remote.username and commit.remote.username != "github-actions" %} by @{{ commit.remote.username }}{%- endif %}\
    {% endfor %}\
{% endfor %}
"""
trim = true
footer = """
"""
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = []
commit_parsers = [
    { message = "^build\\(deps\\)", skip = true },
    { message = "^build\\(deps-dev\\)", skip = true },
    { message = "^ci", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { body = ".*", group = "Changes" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = ".*@v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"
