[workspace]
members = [
    "basis-points",
    "solana-safe-math",
    "wrapped-decimal",
]
default-members = [
    "basis-points",
    "solana-safe-math",
    "wrapped-decimal",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "1.0.1" }
basis-points = { path = "basis-points" }
bytemuck = { version = "1.20.0", features = ["derive", "min_const_generics"] }
codama = { version = "0.9.2" }
rust_decimal = { version = "1.41.0", features = ["maths"] }
thiserror = { version = "2.0.18" }
husky-rs = { version = "0.3.2" }

[workspace.metadata.release]
pre-release-commit-message = "Publish {{crate_name}} v{{version}}"
tag-message = "Publish {{crate_name}} v{{version}}"
consolidate-commits = false
