[workspace]
members = [
    "crates/basis-points",
    "crates/solana-math",
    "crates/wrapped-decimal",
]
default-members = [
    "crates/basis-points",
    "crates/solana-math",
    "crates/wrapped-decimal",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "1.2.0" }
basis-points = { version = "0.4.1", path = "crates/basis-points" }
brine-fp = { version = "0.3.1", default-features = false }
bytemuck = { version = "1.20.0", features = ["derive", "min_const_generics"] }
codama = { version = "0.9.2" }
quasar-lang = { version = "0.0.0" }
rust_decimal = { version = "1.42.0", features = ["maths"] }
# Compatible with anchor-lang, which uses rustc 1.89
ruint = { version = "=1.16.0", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
husky-rs = { version = "0.3.3" }
zeropod = { version = "=0.3.3" }

[workspace.metadata.changeset]
commit = false
tags = false
keep-changesets = false
tag-format = "crate-prefixed"
changelog = "per-package"
comparison-links = "disabled"
zero-version-behavior = "effective-minor"
base-branch = "main"
none-bump-behavior = "promote-to-patch"
