[workspace]
members = [
    "basis-points",
    "solana-safe-math",
    "wrapped-decimal",
]
default-members = [
    "basis-points",
    "solana-safe-math",
    "wrapped-decimal",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "1.0.1" }
bytemuck = { version = "1.20.0", features = ["derive", "min_const_generics"] }
rust_decimal = { version = "1.41.0", features = ["maths"] }
thiserror = { version = "2.0.18" }
cargo-husky = { version = "1", default-features = false, features = ["user-hooks"] }
