[package]
name = "basis-points"
version = "0.1.0"
edition = "2021"

[features]
default = []
anchor = ["dep:anchor-lang"]
decimal = ["dep:rust_decimal"]
idl-build = ["anchor", "anchor-lang/idl-build"]

[dependencies]
anchor-lang = { workspace = true, optional = true }
bytemuck = { workspace = true }
rust_decimal = { workspace = true, optional = true }
thiserror = { workspace = true }
